services:

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: cvision-ai-backend

    ports:
      - "5000:5000"

    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile

    container_name: cvision-ai-frontend

    ports:
      - "8081:80"

    restart: unless-stopped